name: world_tests

on:
  push:
  workflow_dispatch:
  schedule:
    # at 03:00 every day.
    - cron: "0 3 * * *"

env:
  PACKER_VERSION: "1.9.2"
  CORE_ENDPOINT_URL: http://10.20.0.2:80/api/core
  CORE_USERNAME: "admin"
  CORE_PASSWORD: "admin"
  ELEMENT_NAME: world


jobs:
  World_Tests:
    runs-on: ubuntu-24.04
    if : ${{ github.actor != 'dependabot[bot]' }}
    # Temporarily disabled. need disk space.
    # if: ${{ false }}
    steps:
      - name: Check Remaining Disk Space
        run: df -h
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          # Set to true to delete tools you do not need
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Check Remaining Disk Space
        run: df -h
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}
      - name: Install exordos
        run: curl -fsSL https://repo.exordos.com/install.sh | sh
      - name: Install hypervisor
        run: |
          EXORDOS_BIN=$(which exordos)
          sudo $EXORDOS_BIN compute hypervisors init
          sudo chmod 666 /dev/kvm
      - name: set exordos config
        run: |
          exordos settings set-realm default --endpoint $CORE_ENDPOINT_URL
          exordos settings set-context default --name default --user $CORE_USERNAME --password $CORE_PASSWORD
      - name: Bootstrap exordos_core
        run:
          exordos bootstrap -i latest -f -m core --admin-password $CORE_PASSWORD --cidr 10.20.0.0/22
      - name: Wait for Exordos Core API
        run: |
          for i in {1..60}; do
            if exordos ready_api; then
              echo "Exordos Core API is ready"
              break
            fi
            echo "Waiting for Exordos Core API... ($i/60)"
            sleep 5
          done
      - name: Set hypervisor with overbooking
        run: |
          HYPER_UUID="$(exordos c h l -o json | jq -r .[0]."uuid")"
          exordos compute hypervisors update $HYPER_UUID --cores-ratio 10.0 --ram-ratio 10.0
      - name: install world
        run: exordos e e install $ELEMENT_NAME
      - name: check exordos world
        timeout-minutes: 10
        run: |
          set -eux

          while [ $(exordos ee l -o json -f name=$ELEMENT_NAME | jq -r .[0]."status") != "ACTIVE" ]; do
            sleep 5
          done

          exordos e e show $ELEMENT_NAME
      - name: Setup upterm session
        uses: owenthereal/action-upterm@v1
        if: ${{ failure() }}
        with:
          limit-access-to-actor: true
          wait-timeout-minutes: 15
